# Generated by Django 3.1.14 on 2024-12-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20241227_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.TextField(max_length=250),
        ),
    ]
