# Generated by Django 3.1.14 on 2025-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20241228_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.TextField(max_length=350),
        ),
    ]
